### ISSUE TITLE
Contact Michael E-Smith to engage AIATSIS with ICSM

### ISSUE THREAD

**Issue by Metaduck** [idn-au/.github#33]

**Comment by nicholascar** [comment]
Emailed Michael today asking him to help arrange for AIATSIS members to attend the next PCPN meeting

**Comment by Metaduck** [comment]
Rafe Benali (Vic place names) - Chair of ICSM GPN

Jay Dominic (has left AIATSIS) - and possibly only Jaimie Solvens is left.
