### ISSUE TITLE
Follow up with Find-An-Expert for data reuse for AgentsDB

### ISSUE THREAD

**Issue by nicholascar** [idn-au/.github#47]
Melbourne Uni equivalence to the researcher Profile

**Comment by Metaduck** [comment]
There is a DB at UniMelb that gives the researcher profiles at the Uni. Looking specifically to have Indigenous researchers indicated in the AgentsDB.

May also need to extend the terminology/vocabulary to classify the researchers. 

Example: https://findanexpert.unimelb.edu.au/profile/5922-les-kneebone

**Comment by lalewis1** [comment]
found existing indigenous category

https://findanexpert.unimelb.edu.au/searchresults?q=Indigenous%20studies&category=profile

todo: port researchers across to agents DB

**Comment by lalewis1** [comment]
I have emailed Uni Melb to see if they can provide some kind of export. website does not provide this facility and data quality will be higher if an export can be provided.

**Comment by Metaduck** [comment]
They have a characterisation in the list for Indigenous Research Experts.
Queried how this information could be accessed - need to ask each researcher individually if they are happy to be brought into the database.
Nick has suggested the following: 
- Talk with Kristen to see the way to progress.
- May need to add to the vocabularies to classify these positions separately - may not need names
- potentially via an anonymised IDs or via OrcIDs

**Comment by lalewis1** [comment]
This task has evolved into #88
